In [6]:
import pandas as pd

df = pd.read_csv("zomato.csv")

df.head()

,Unnamed: 0.1,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,0,0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,3,3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,4,4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur

In [7]:
df.isnull().sum()

Unnamed: 0.1              0
Unnamed: 0                0
restaurant name           0
restaurant type           0
rate (out of 5)          68
num of ratings            0
avg cost (two people)    57
online_order              0
table booking             0
cuisines type             0
area                      0
local address             0
dtype: int64

In [9]:
df=df.dropna(subset=['rate (out of 5)', 'avg cost (two people)'])

df.isnull().sum()

# I've decided to drop the rows which contained null values for rating and avg cost as the number of null values are 125,
# which is insignificant in comparison to our dataset. Also either changing the rating to the average or '0' would skew the results.
# Similarly with avg cost there is no way of estimating an avg cost for a restaurant as they may vary vastly.

Unnamed: 0.1             0
Unnamed: 0               0
restaurant name          0
restaurant type          0
rate (out of 5)          0
num of ratings           0
avg cost (two people)    0
online_order             0
table booking            0
cuisines type            0
area                     0
local address            0
dtype: int64

In [10]:
df = df.drop_duplicates()

In [12]:
df['restaurant name'] = df['restaurant name'].str.strip()
df['area'] = df['area'].str.title()

# convert avg cost into int for correct calculations
df['avg cost (two people)'] = df['avg cost (two people)'].astype(int)

In [13]:
df['cost_per_person'] = df['avg cost (two people)']/2

def categorize_rating(rating):
  if rating >= 4.5:
    return "Very Good"
  elif rating >= 3.5:
    return "Good"
  elif rating >= 2.5:
    return "Average"
  else:
    return "Poor"

df['rating_category'] = df['rate (out of 5)'].apply(categorize_rating)

In [14]:
df.to_csv("cleaned_dataset.csv")